using System;
using System.Collections.Generic;
using System.ComponentModel.Design;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Navigation;
using System.Windows.Shapes;

namespace AplicationForStoreOrderMaking.Pages1
{
    public partial class YourOrders : Page
    {
        List<string> PrimarykeyTovars = new List<string>();
        List<string> index = new List<string>();
        List<string> namesOfTovars = new List<string>();
        List<int> differentNumbers = new List<int>();
        string AdressStroka = "";
        string DoubleInfoStroka = "";
        int random = 0;
        Random rnd = new Random();
        List<int> indexes = new List<int>();
        int counterOfIndex = 10;
        static string connectionString = ConfigurationManager.ConnectionStrings["SqlConnection"].ConnectionString;
        SqlConnection cnn = new SqlConnection(connectionString);
        public YourOrders()
        {
            InitializeComponent();
            Cb1.Visibility = Visibility.Hidden;
            Cb2.Visibility = Visibility.Hidden;
            Cb3.Visibility = Visibility.Hidden;
            Cb4.Visibility = Visibility.Hidden;
            Cb5.Visibility = Visibility.Hidden;
            Cb6.Visibility = Visibility.Hidden;
            Cb7.Visibility = Visibility.Hidden;
            Cb8.Visibility = Visibility.Hidden;
            Cb9.Visibility = Visibility.Hidden;
            Cb10.Visibility = Visibility.Hidden;
            Tb1.IsEnabled = false;
            Tb2.IsEnabled = false;
            Tb3.IsEnabled = false;
            Tb4.IsEnabled = false;
            Tb5.IsEnabled = false;
            Tb6.IsEnabled = false;
            Tb7.IsEnabled = false;
            Tb8.IsEnabled = false;
            Tb9.IsEnabled = false;
            Tb10.IsEnabled = false;
            Tb1.Text = 0.ToString();
            Tb2.Text = 0.ToString();
            Tb3.Text = 0.ToString();
            Tb4.Text = 0.ToString();
            Tb5.Text = 0.ToString();
            Tb6.Text = 0.ToString();
            Tb7.Text = 0.ToString();
            Tb8.Text = 0.ToString();
            Tb9.Text = 0.ToString();
            Tb10.Text = 0.ToString();
            BtMinus1.IsEnabled = false;
            BtMinus2.IsEnabled = false;
            BtMinus3.IsEnabled = false;
            BtMinus4.IsEnabled = false;
            BtMinus5.IsEnabled = false;
            BtMinus6.IsEnabled = false;
            BtMinus7.IsEnabled = false;
            BtMinus8.IsEnabled = false;
            BtMinus9.IsEnabled = false;
            BtMinus10.IsEnabled = false;
            BtPlus1.IsEnabled = false;
            BtPlus2.IsEnabled = false;
            BtPlus3.IsEnabled = false;
            BtPlus4.IsEnabled = false;
            BtPlus5.IsEnabled = false;
            BtPlus6.IsEnabled = false;
            BtPlus7.IsEnabled = false;
            BtPlus8.IsEnabled = false;
            BtPlus9.IsEnabled = false;
            BtPlus10.IsEnabled = false;
            Tb1.Visibility = Visibility.Hidden;
            Tb2.Visibility = Visibility.Hidden;
            Tb3.Visibility = Visibility.Hidden;
            Tb4.Visibility = Visibility.Hidden;
            Tb5.Visibility = Visibility.Hidden;
            Tb6.Visibility = Visibility.Hidden;
            Tb7.Visibility = Visibility.Hidden;
            Tb8.Visibility = Visibility.Hidden;
            Tb9.Visibility = Visibility.Hidden;
            Tb10.Visibility = Visibility.Hidden;
            BtMinus1.Visibility = Visibility.Hidden;
            BtMinus2.Visibility = Visibility.Hidden;
            BtMinus3.Visibility = Visibility.Hidden;
            BtMinus4.Visibility = Visibility.Hidden;
            BtMinus5.Visibility = Visibility.Hidden;
            BtMinus6.Visibility = Visibility.Hidden;
            BtMinus7.Visibility = Visibility.Hidden;
            BtMinus8.Visibility = Visibility.Hidden;
            BtMinus9.Visibility = Visibility.Hidden;
            BtMinus10.Visibility = Visibility.Hidden;
            BtPlus1.Visibility = Visibility.Hidden;
            BtPlus2.Visibility = Visibility.Hidden;
            BtPlus3.Visibility = Visibility.Hidden;
            BtPlus4.Visibility = Visibility.Hidden;
            BtPlus5.Visibility = Visibility.Hidden;
            BtPlus6.Visibility = Visibility.Hidden;
            BtPlus7.Visibility = Visibility.Hidden;
            BtPlus8.Visibility = Visibility.Hidden;
            BtPlus9.Visibility = Visibility.Hidden;
            BtPlus10.Visibility = Visibility.Hidden;
            ListOfOrders.IsEnabled = false;
            ShowTovarsBT.Visibility = Visibility.Hidden;
            ListBoxTovars.Visibility = Visibility.Hidden;
            SqlConnection cnn = new SqlConnection(connectionString);
            cnn.Open();
            SqlCommand cmd = cnn.CreateCommand();
            cmd.CommandText = @"Select Номер_заказа from Заказы";
            SqlDataReader r = cmd.ExecuteReader();
            OrdersIsDoneLB.Items.Clear();
            while (r.Read())
                OrdersIsDoneLB.Items.Add(String.Format("{0}", r.GetValue(0).ToString()));
            r.Close();
        }

        private void Button_Click(object sender, RoutedEventArgs e)
        {
            PrimarykeyTovars.Clear();
            namesOfTovars.Clear();
            ListOfOrders.Items.Clear();
            Cb1.Visibility = Visibility.Hidden;
            Cb2.Visibility = Visibility.Hidden;
            Cb3.Visibility = Visibility.Hidden;
            Cb4.Visibility = Visibility.Hidden;
            Cb5.Visibility = Visibility.Hidden;
            Cb6.Visibility = Visibility.Hidden;
            Cb7.Visibility = Visibility.Hidden;
            Cb8.Visibility = Visibility.Hidden;
            Cb9.Visibility = Visibility.Hidden;
            Cb10.Visibility = Visibility.Hidden;
            Tb1.IsEnabled = false;
            Tb2.IsEnabled = false;
            Tb3.IsEnabled = false;
            Tb4.IsEnabled = false;
            Tb5.IsEnabled = false;
            Tb6.IsEnabled = false;
            Tb7.IsEnabled = false;
            Tb8.IsEnabled = false;
            Tb9.IsEnabled = false;
            Tb10.IsEnabled = false;
            Tb1.Text = 0.ToString();
            Tb2.Text = 0.ToString();
            Tb3.Text = 0.ToString();
            Tb4.Text = 0.ToString();
            Tb5.Text = 0.ToString();
            Tb6.Text = 0.ToString();
            Tb7.Text = 0.ToString();
            Tb8.Text = 0.ToString();
            Tb9.Text = 0.ToString();
            Tb10.Text = 0.ToString();
            BtMinus1.IsEnabled = false;
            BtMinus2.IsEnabled = false;
            BtMinus3.IsEnabled = false;
            BtMinus4.IsEnabled = false;
            BtMinus5.IsEnabled = false;
            BtMinus6.IsEnabled = false;
            BtMinus7.IsEnabled = false;
            BtMinus8.IsEnabled = false;
            BtMinus9.IsEnabled = false;
            BtMinus10.IsEnabled = false;
            BtPlus1.IsEnabled = false;
            BtPlus2.IsEnabled = false;
            BtPlus3.IsEnabled = false;
            BtPlus4.IsEnabled = false;
            BtPlus5.IsEnabled = false;
            BtPlus6.IsEnabled = false;
            BtPlus7.IsEnabled = false;
            BtPlus8.IsEnabled = false;
            BtPlus9.IsEnabled = false;
            BtPlus10.IsEnabled = false;
            Tb1.Visibility = Visibility.Hidden;
            Tb2.Visibility = Visibility.Hidden;
            Tb3.Visibility = Visibility.Hidden;
            Tb4.Visibility = Visibility.Hidden;
            Tb5.Visibility = Visibility.Hidden;
            Tb6.Visibility = Visibility.Hidden;
            Tb7.Visibility = Visibility.Hidden;
            Tb8.Visibility = Visibility.Hidden;
            Tb9.Visibility = Visibility.Hidden;
            Tb10.Visibility = Visibility.Hidden;
            BtMinus1.Visibility = Visibility.Hidden;
            BtMinus2.Visibility = Visibility.Hidden;
            BtMinus3.Visibility = Visibility.Hidden;
            BtMinus4.Visibility = Visibility.Hidden;
            BtMinus5.Visibility = Visibility.Hidden;
            BtMinus6.Visibility = Visibility.Hidden;
            BtMinus7.Visibility = Visibility.Hidden;
            BtMinus8.Visibility = Visibility.Hidden;
            BtMinus9.Visibility = Visibility.Hidden;
            BtMinus10.Visibility = Visibility.Hidden;
            BtPlus1.Visibility = Visibility.Hidden;
            BtPlus2.Visibility = Visibility.Hidden;
            BtPlus3.Visibility = Visibility.Hidden;
            BtPlus4.Visibility = Visibility.Hidden;
            BtPlus5.Visibility = Visibility.Hidden;
            BtPlus6.Visibility = Visibility.Hidden;
            BtPlus7.Visibility = Visibility.Hidden;
            BtPlus8.Visibility = Visibility.Hidden;
            BtPlus9.Visibility = Visibility.Hidden;
            BtPlus10.Visibility = Visibility.Hidden;
            ListOfOrders.IsEnabled = false;
            ShowTovarsBT.Visibility = Visibility.Hidden;
            ListBoxTovars.Visibility = Visibility.Hidden;
            ListOfOrders.Items.Clear();
            int index = Convert.ToInt32(OrdersIsDoneLB.SelectedValue);
            SqlConnection cnn = new SqlConnection(connectionString);
            cnn.Open();
            SqlCommand command = cnn.CreateCommand();
            command.CommandText = "Select Срок_сборки from Заказы where Номер_заказа =" + index;
            SqlDataReader r = command.ExecuteReader();
            int number = 0;
            while (r.Read())
                number = Convert.ToInt32(String.Format("{0}", r.GetValue(0).ToString()));
            r.Close();
            if (number == 0)
            {
                MessageBox.Show("Срок сборки истек!", "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
                ShowTovarsBT.Visibility = Visibility.Hidden;
                ListBoxTovars.Visibility = Visibility.Hidden;
            }
            else
            {
                MessageBox.Show("Срок сборки не истек!", "Успешно", MessageBoxButton.OK, MessageBoxImage.Information);
                SqlCommand command1 = cnn.CreateCommand();
                command1.CommandText = "Select Код_товара from Содержимое_заказов where Номер_заказа =" + index;
                SqlDataReader r1 = command1.ExecuteReader();
                while (r1.Read())
                    PrimarykeyTovars.Add(String.Format("{0}", r1.GetValue(0).ToString()));
                r1.Close();
                foreach (string str in PrimarykeyTovars)
                {
                    SqlCommand command2 = cnn.CreateCommand();
                    command2.CommandText = @"Select Название from Товары where Код_товара =" + Convert.ToInt32(str);
                    SqlDataReader r2 = command2.ExecuteReader();
                    while (r2.Read())
                        namesOfTovars.Add(String.Format("{0}", r2.GetValue(0).ToString()));
                    r2.Close();
                }
                int counter = 0;
                foreach(string str2 in PrimarykeyTovars)
                {
                    ListOfOrders.Items.Add(str2 + "." + namesOfTovars[counter]);
                    counter++;
                }
                switch(PrimarykeyTovars.Count())
                {
                    case 9:
                        counterOfIndex -= 1;
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        BtMinus7.IsEnabled = true;
                        BtPlus7.IsEnabled = true;
                        Tb7.Text = 1.ToString();
                        Tb7.Visibility = Visibility.Visible;
                        BtPlus7.Visibility = Visibility.Visible;
                        BtMinus7.Visibility = Visibility.Visible;
                        Cb7.Visibility = Visibility.Visible;
                        Cb7.SelectedIndex = 1;
                        BtMinus8.IsEnabled = true;
                        BtPlus8.IsEnabled = true;
                        Tb8.Text = 1.ToString();
                        Tb8.Visibility = Visibility.Visible;
                        BtPlus8.Visibility = Visibility.Visible;
                        BtMinus8.Visibility = Visibility.Visible;
                        Cb8.Visibility = Visibility.Visible;
                        Cb8.SelectedIndex = 1;
                        BtMinus9.IsEnabled = true;
                        BtPlus9.IsEnabled = true;
                        Tb9.Text = 1.ToString();
                        Tb9.Visibility = Visibility.Visible;
                        BtPlus9.Visibility = Visibility.Visible;
                        BtMinus9.Visibility = Visibility.Visible;
                        Cb9.Visibility = Visibility.Visible;
                        Cb9.SelectedIndex = 1;
                        break;
                    case 8:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        BtMinus7.IsEnabled = true;
                        BtPlus7.IsEnabled = true;
                        Tb7.Text = 1.ToString();
                        Tb7.Visibility = Visibility.Visible;
                        BtPlus7.Visibility = Visibility.Visible;
                        BtMinus7.Visibility = Visibility.Visible;
                        Cb7.Visibility = Visibility.Visible;
                        Cb7.SelectedIndex = 1;
                        BtMinus8.IsEnabled = true;
                        BtPlus8.IsEnabled = true;
                        Tb8.Text = 1.ToString();
                        Tb8.Visibility = Visibility.Visible;
                        BtPlus8.Visibility = Visibility.Visible;
                        BtMinus8.Visibility = Visibility.Visible;
                        Cb8.Visibility = Visibility.Visible;
                        Cb8.SelectedIndex = 1;
                        break;
                    case 7:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        BtMinus7.IsEnabled = true;
                        BtPlus7.IsEnabled = true;
                        Tb7.Text = 1.ToString();
                        Tb7.Visibility = Visibility.Visible;
                        BtPlus7.Visibility = Visibility.Visible;
                        BtMinus7.Visibility = Visibility.Visible;
                        Cb7.Visibility = Visibility.Visible;
                        Cb7.SelectedIndex = 1;
                        break;
                    case 6:
                        ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        counterOfIndex -= 1;
                        indexes.Add(ListBoxTovars.SelectedIndex);
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        break;
                    case 5:
                        ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        counterOfIndex -= 1;
                        indexes.Add(ListBoxTovars.SelectedIndex);
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        break;
                    case 4:
                        ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        counterOfIndex -= 1;
                        indexes.Add(ListBoxTovars.SelectedIndex);
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        break;
                    case 3:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        break;
                    case 2:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        break;
                    case 1:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        break;
                    case 10:
                        BtMinus1.IsEnabled = true;
                        BtPlus1.IsEnabled = true;
                        Tb1.Text = 1.ToString();
                        Tb1.Visibility = Visibility.Visible;
                        BtPlus1.Visibility = Visibility.Visible;
                        BtMinus1.Visibility = Visibility.Visible;
                        Cb1.Visibility = Visibility.Visible;
                        Cb1.SelectedIndex = 1;
                        BtMinus2.IsEnabled = true;
                        BtPlus2.IsEnabled = true;
                        Tb2.Text = 1.ToString();
                        Tb2.Visibility = Visibility.Visible;
                        BtPlus2.Visibility = Visibility.Visible;
                        BtMinus2.Visibility = Visibility.Visible;
                        Cb2.Visibility = Visibility.Visible;
                        Cb2.SelectedIndex = 1;
                        BtMinus3.IsEnabled = true;
                        BtPlus3.IsEnabled = true;
                        Tb3.Text = 1.ToString();
                        Tb3.Visibility = Visibility.Visible;
                        BtPlus3.Visibility = Visibility.Visible;
                        BtMinus3.Visibility = Visibility.Visible;
                        Cb3.Visibility = Visibility.Visible;
                        Cb3.SelectedIndex = 1;
                        BtMinus4.IsEnabled = true;
                        BtPlus4.IsEnabled = true;
                        Tb4.Text = 1.ToString();
                        Tb4.Visibility = Visibility.Visible;
                        BtPlus4.Visibility = Visibility.Visible;
                        BtMinus4.Visibility = Visibility.Visible;
                        Cb4.Visibility = Visibility.Visible;
                        Cb4.SelectedIndex = 1;
                        BtMinus5.IsEnabled = true;
                        BtPlus5.IsEnabled = true;
                        Tb5.Text = 1.ToString();
                        Tb5.Visibility = Visibility.Visible;
                        BtPlus5.Visibility = Visibility.Visible;
                        BtMinus5.Visibility = Visibility.Visible;
                        Cb5.Visibility = Visibility.Visible;
                        Cb5.SelectedIndex = 1;
                        BtMinus6.IsEnabled = true;
                        BtPlus6.IsEnabled = true;
                        Tb6.Text = 1.ToString();
                        Tb6.Visibility = Visibility.Visible;
                        BtPlus6.Visibility = Visibility.Visible;
                        BtMinus6.Visibility = Visibility.Visible;
                        Cb6.Visibility = Visibility.Visible;
                        Cb6.SelectedIndex = 1;
                        BtMinus7.IsEnabled = true;
                        BtPlus7.IsEnabled = true;
                        Tb7.Text = 1.ToString();
                        Tb7.Visibility = Visibility.Visible;
                        BtPlus7.Visibility = Visibility.Visible;
                        BtMinus7.Visibility = Visibility.Visible;
                        Cb7.Visibility = Visibility.Visible;
                        Cb7.SelectedIndex = 1;
                        BtMinus8.IsEnabled = true;
                        BtPlus8.IsEnabled = true;
                        Tb8.Text = 1.ToString();
                        Tb8.Visibility = Visibility.Visible;
                        BtPlus8.Visibility = Visibility.Visible;
                        BtMinus8.Visibility = Visibility.Visible;
                        Cb8.Visibility = Visibility.Visible;
                        Cb8.SelectedIndex = 1;
                        BtMinus9.IsEnabled = true;
                        BtPlus9.IsEnabled = true;
                        Tb9.Text = 1.ToString();
                        Tb9.Visibility = Visibility.Visible;
                        BtPlus9.Visibility = Visibility.Visible;
                        BtMinus9.Visibility = Visibility.Visible;
                        Cb9.Visibility = Visibility.Visible;
                        Cb9.SelectedIndex = 1;
                        BtMinus10.IsEnabled = true;
                        BtPlus10.IsEnabled = true;
                        Tb10.Text = 1.ToString();
                        Tb10.Visibility = Visibility.Visible;
                        BtPlus10.Visibility = Visibility.Visible;
                        BtMinus10.Visibility = Visibility.Visible;
                        Cb10.Visibility = Visibility.Visible;
                        Cb10.SelectedIndex = 1;
                        break;
                    default:
                        break;
                }
                counterOfIndex = counterOfIndex - PrimarykeyTovars.Count();
                ShowTovarsBT.Visibility = Visibility.Visible;
                ListBoxTovars.Visibility = Visibility.Visible;
            }
            cnn.Close();
        }

        private void Button_Click_1(object sender, RoutedEventArgs e)
        {
            cnn.Open();
            List<string> names = new List<string>();
            SqlCommand command = cnn.CreateCommand();
            command.CommandText = @"Select Код_товара from Товары";
            SqlDataReader reader = command.ExecuteReader();
            while (reader.Read())
                names.Add(String.Format("{0}", reader.GetValue(0).ToString()));
            reader.Close();
            SqlCommand command1 = cnn.CreateCommand();
            command1.CommandText = @"Select Название from Товары";
            SqlDataReader reader1 = command1.ExecuteReader();
            ListBoxTovars.Items.Clear();
            int i = 0;
            while (reader1.Read())
            {
                ListBoxTovars.Items.Add(names[i] + "." + String.Format("{0}", reader1.GetValue(0).ToString()));
                i++;
            }
            reader1.Close();
            cnn.Close();
        }

        private void Button_Click_2(object sender, RoutedEventArgs e)
        {
            List<string> index = new List<string>();
            if (ListBoxTovars.SelectedIndex == -1)
            {
                MessageBox.Show("Вы не выбрали товар!", "Ошибка", MessageBoxButton.OK, MessageBoxImage.Error);
            }
            else
            {
                index.Add(ListBoxTovars.SelectedItem.ToString());
                for (int i = 0; i < index.Count(); i++)
                {
                    string c = index[i];
                    if (ListOfOrders.Items.Contains(c))
                    {
                        MessageBox.Show("Нельзя добавлять один и тот же товар дважды", "Ошибка!", MessageBoxButton.OK, MessageBoxImage.Error);
                    }
                    else
                    {
                        switch (counterOfIndex)
                        {
                            case 9:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus1.IsEnabled = true;
                                BtPlus1.IsEnabled = true;
                                Tb1.Text = 1.ToString();
                                Tb1.Visibility = Visibility.Visible;
                                BtPlus1.Visibility = Visibility.Visible;
                                BtMinus1.Visibility = Visibility.Visible;
                                Cb1.Visibility = Visibility.Visible;
                                Cb1.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 8:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus2.IsEnabled = true;
                                BtPlus2.IsEnabled = true;
                                Tb2.Text = 1.ToString();
                                Tb2.Visibility = Visibility.Visible;
                                BtPlus2.Visibility = Visibility.Visible;
                                BtMinus2.Visibility = Visibility.Visible;
                                Cb2.Visibility = Visibility.Visible;
                                Cb2.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 7:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus3.IsEnabled = true;
                                BtPlus3.IsEnabled = true;
                                Tb3.Text = 1.ToString();
                                Tb3.Visibility = Visibility.Visible;
                                BtPlus3.Visibility = Visibility.Visible;
                                BtMinus3.Visibility = Visibility.Visible;
                                Cb3.Visibility = Visibility.Visible;
                                Cb3.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 6:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus4.IsEnabled = true;
                                BtPlus4.IsEnabled = true;
                                Tb4.Text = 1.ToString();
                                Tb4.Visibility = Visibility.Visible;
                                BtPlus4.Visibility = Visibility.Visible;
                                BtMinus4.Visibility = Visibility.Visible;
                                Cb4.Visibility = Visibility.Visible;
                                Cb4.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 5:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus5.IsEnabled = true;
                                BtPlus5.IsEnabled = true;
                                Tb5.Text = 1.ToString();
                                Tb5.Visibility = Visibility.Visible;
                                BtPlus5.Visibility = Visibility.Visible;
                                BtMinus5.Visibility = Visibility.Visible;
                                Cb5.Visibility = Visibility.Visible;
                                Cb5.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 4:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus6.IsEnabled = true;
                                BtPlus6.IsEnabled = true;
                                Tb6.Text = 1.ToString();
                                Tb6.Visibility = Visibility.Visible;
                                BtPlus6.Visibility = Visibility.Visible;
                                BtMinus6.Visibility = Visibility.Visible;
                                Cb6.Visibility = Visibility.Visible;
                                Cb6.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 3:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus7.IsEnabled = true;
                                BtPlus7.IsEnabled = true;
                                Tb7.Text = 1.ToString();
                                Tb7.Visibility = Visibility.Visible;
                                BtPlus7.Visibility = Visibility.Visible;
                                BtMinus7.Visibility = Visibility.Visible;
                                Cb7.Visibility = Visibility.Visible;
                                Cb7.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 2:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus8.IsEnabled = true;
                                BtPlus8.IsEnabled = true;
                                Tb8.Text = 1.ToString();
                                Tb8.Visibility = Visibility.Visible;
                                BtPlus8.Visibility = Visibility.Visible;
                                BtMinus8.Visibility = Visibility.Visible;
                                Cb8.Visibility = Visibility.Visible;
                                Cb8.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 1:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus9.IsEnabled = true;
                                BtPlus9.IsEnabled = true;
                                Tb9.Text = 1.ToString();
                                Tb9.Visibility = Visibility.Visible;
                                BtPlus9.Visibility = Visibility.Visible;
                                BtMinus9.Visibility = Visibility.Visible;
                                Cb9.Visibility = Visibility.Visible;
                                Cb9.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                indexes.Add(ListBoxTovars.SelectedIndex);
                                break;
                            case 0:
                                ListOfOrders.Items.Add(ListBoxTovars.SelectedItem);
                                BtMinus10.IsEnabled = true;
                                BtPlus10.IsEnabled = true;
                                Tb10.Text = 1.ToString();
                                Tb10.Visibility = Visibility.Visible;
                                BtPlus10.Visibility = Visibility.Visible;
                                BtMinus10.Visibility = Visibility.Visible;
                                Cb10.Visibility = Visibility.Visible;
                                Cb10.SelectedIndex = 1;
                                counterOfIndex -= 1;
                                break;
                            case 10:
                                break;
                            default:
                                counterOfIndex = 10;
                                break;
                        }
                    }
                }
            }
        }
    }
}
